######################################################################
# Automatically generated by qmake (3.0) ?? ????. 22 15:40:35 2016
######################################################################

TEMPLATE = app
TARGET = 10_small_application_with_signal_and_slots
INCLUDEPATH += .

# Input
HEADERS += Counter.hpp
SOURCES += Counter.cpp main.cpp
