######################################################################
# Automatically generated by qmake (3.0) ?? ???. 16 00:41:04 2015
######################################################################

TEMPLATE = app
TARGET = 1
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += hello.cpp
